name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: loayshaqir/nbdev_ci_image
    steps: [uses: fastai/workflows/nbdev-ci@master]