name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: loayshaqir/nbdev_ci_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Move to spanner_workbench Directory
        run: cd nbdev_spanner_workbench
      - name: Use nbdev CI Workflow
        uses: fastai/workflows/nbdev-ci@master
